import 'package:intl_phone_field/countries.dart';

const canada = Country(
  name: "Canada",
  nameTranslations: {
    "sk": "Kanada",
    "se": "Kanáda",
    "pl": "Kanada",
    "no": "Canada",
    "ja": "カナダ",
    "it": "Canada",
    "zh": "加拿大",
    "nl": "Canada",
    "de": "Kanada",
    "fr": "Canada",
    "es": "Canadá",
    "en": "Canada",
    "pt_BR": "Canadá",
    "sr-Cyrl": "Канада",
    "sr-Latn": "Kanada",
    "zh_TW": "加拿大",
    "tr": "Kanada",
    "ro": "Canada",
    "ar": "كندا",
    "fa": "کانادا",
    "yue": "加拿大"
  },
  flag: "🇨🇦",
  code: "CA",
  dialCode: "1",
  minLength: 10,
  maxLength: 10,
);

const us = Country(
  name: "United States",
  nameTranslations: {
    "sk": "Spojené štáty",
    "se": "Amerihká ovttastuvvan stáhtat",
    "pl": "Stany Zjednoczone",
    "no": "USA",
    "ja": "アメリカ合衆国",
    "it": "Stati Uniti",
    "zh": "美国",
    "nl": "Verenigde Staten",
    "de": "Vereinigte Staaten",
    "fr": "États-Unis",
    "es": "Estados Unidos",
    "en": "United States",
    "pt_BR": "Estados Unidos",
    "sr-Cyrl": "Сједињене Америчке Државе",
    "sr-Latn": "Sjedinjene Američke Države",
    "zh_TW": "美國",
    "tr": "Amerika Birleşik Devletleri",
    "ro": "Statele Unite ale Americii",
    "ar": "الولايات المتحدة",
    "fa": "ایالات متحده آمریکا",
    "yue": "美利堅郃眾囯"
  },
  flag: "🇺🇸",
  code: "US",
  dialCode: "1",
  minLength: 10,
  maxLength: 10,
);
